version: '2'
services:
    tsalefkarhba-app:
        image: tsalefkarhba
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://tsalefkarhba-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=tsalefKarhba
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=tsalefkarhba-elasticsearch:9300
        ports:
            - 8080:8080
    tsalefkarhba-mongodb:
        extends:
            file: mongodb.yml
            service: tsalefkarhba-mongodb
    tsalefkarhba-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: tsalefkarhba-elasticsearch
